name: C/C++ CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install libs
      run:
        sudo apt install -y libav-tools  
    - name: Build
      run: make
      
    - name: Commit files
      run:
        git config --local user.email "githubActions"
        git config --local user.name "Auto Build Action"
        git commit -m "Build"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: release
        force: true
